server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/link_shortener
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/link_shortener
    user: postgres
    password: password